const weapons = {
  broken_sword: {
    id: "broken_sword",
    price: 10,
    speed: 0,
    atk: 5,
    stackable: true,
    icon: "gfx/items/shattered-sword.png",
    tier: itemTiers.common,
    type: "weapon",
  },
  broken_mace: {
    id: "broken_mace",
    price: 10,
    speed: -5,
    atk: 6,
    stackable: true,
    icon: "gfx/items/bone-mace.png",
    tier: itemTiers.common,
    type: "weapon",
  },
  long_sword: {
    id: "long_sword",
    price: 120,
    speed: 2,
    atk: 8,
    stackable: true,
    icon: "gfx/items/broadsword.png",
    tier: itemTiers.uncommon,
    type: "weapon",
  },
  battle_axe: {
    id: "battle_axe",
    price: 150,
    speed: -5,
    atk: 12,
    stackable: true,
    icon: "gfx/items/sharp-axe.png",
    tier: itemTiers.uncommon,
    type: "weapon",
  },
  dual_daggers: {
    id: "dual_daggers",
    price: 150,
    speed: 8,
    atk: 7,
    stackable: true,
    icon: "gfx/icons/crossed-swords.png",
    tier: itemTiers.uncommon,
    type: "weapon",
  },
  enchanted_blade: {
    id: "enchanted_blade",
    price: 800,
    speed: 5,
    atk: 20,
    stackable: true,
    icon: "gfx/items/broadsword.png",
    tier: itemTiers.rare,
    type: "weapon",
  },
  greatsword: {
    id: "greatsword",
    price: 900,
    speed: -5,
    atk: 30,
    stackable: true,
    icon: "gfx/items/relic-blade.png",
    tier: itemTiers.rare,
    type: "weapon",
  },
  executioner: {
    id: "executioner",
    price: 1000,
    speed: -10,
    atk: 35,
    stackable: true,
    icon: "gfx/items/dripping-sword.png",
    tier: itemTiers.rare,
    type: "weapon",
  },
  dagger_of_speed: {
    id: "dagger_of_speed",
    price: 1000,
    speed: 15,
    atk: 18,
    stackable: true,
    icon: "gfx/items/plain-dagger.png",
    tier: itemTiers.rare,
    type: "weapon",
    modifiers: {
      critRateV: 5,
    },
  },
  astral_spear: {
    id: "astral_spear",
    price: 3000,
    speed: 5,
    atk: 50,
    stackable: true,
    icon: "gfx/items/spear-hook.png",
    tier: itemTiers.epic,
    type: "weapon",
    modifiers: {
      spiP: 5,
    },
  },
};

const armors = {
  ragged_armor: {
    id: "ragged_armor",
    price: 10,
    speed: 0,
    defence: {
      physical: 2,
      magical: 2,
      elemental: 0,
    },
    stackable: true,
    tier: itemTiers.uncommon,
    type: "armor",
    slot: "armor",
  },
  ragged_hood: {
    id: "ragged_hood",
    price: 8,
    speed: 0,
    defence: {
      physical: 1,
      magical: 1,
      elemental: 0,
    },
    stackable: true,
    tier: itemTiers.common,
    type: "armor",
    slot: "helmet",
  },
  ragged_boots: {
    id: "ragged_boots",
    price: 8,
    speed: 0,
    defence: {
      physical: 1,
      magical: 1,
      elemental: 0,
    },
    stackable: true,
    tier: itemTiers.common,
    type: "armor",
    slot: "legs",
  },
};

const materials = {
  bone: {
    id: "bone",
    price: 3,
    stackable: true,
    tier: itemTiers.common,
    type: "material",
  },
};

const items = {
  ...weapons,
  ...armors,
  ...materials,
} as const;
