const enemies = {
  skeleton: {
    id: "skeleton",
    name: "Skeleton",
    stats: {
      str: 5,
      vit: 5,
      agi: 0,
      int: 5,
      spi: 0,
      atk: 5,
      hp: 0,
      mp: 0,
      hpMax: 0,
      mpMax: 0,
      ap: 0,
    },
    defences: {
      physical: 0,
      magical: 0,
      elemental: 0,
    },
    resistances: {
      fire: 0,
      ice: 25,
      thunder: 0,
      curse: 200,
      poison: 100,
      bleed: 100,
      divine: -50,
      stun: 0,
    },
    critRate: 3,
    critPower: 50,
    sprite: "skeleton_type/skeleton_warrior.png",
    abilities: [{ ...abilities.physical_attack }],
    loot: [
      {
        gold: [1, 5],
      },
      {
        item: items.bone,
        chance: 0.5,
        amount: [1, 3],
      },
    ],
  },
  skeleton_brute: {
    id: "skeleton_brute",
    name: "Skeleton Brute",
    stats: {
      str: 10,
      vit: 10,
      agi: -5,
      int: 0,
      spi: 0,
      atk: 10,
      hp: 0,
      mp: 0,
      hpMax: 0,
      mpMax: 0,
      ap: 0,
    },
    defences: {
      physical: 15,
      magical: 10,
      elemental: 15,
    },
    resistances: {
      fire: 0,
      ice: 25,
      thunder: 0,
      curse: 200,
      poison: 100,
      bleed: 100,
      divine: -50,
      stun: 0,
    },
    critRate: 3,
    critPower: 50,
    sprite: "skeleton_type/skeleton_brute.png",
    abilities: [{ ...abilities.physical_attack }],
    loot: [
      {
        gold: [5, 10],
      },
      {
        item: items.bone,
        chance: 0.75,
        amount: [1, 4],
      },
    ],
  },
};
