"use strict";
const merchant = {
    inventoryDefault: [
        { item: items.broken_sword, price: 20 },
        { item: items.broken_mace, price: 20 },
        { item: items.long_sword, price: 200 },
        { item: items.battle_axe, price: 250 },
        { item: items.dual_daggers, price: 250 },
        { item: items.great_shield, price: 1000 },
        { item: items.enchanted_blade, price: 1200 },
        { item: items.greatsword, price: 1500 },
        { item: items.executioner, price: 1500 },
        { item: items.dagger_of_speed, price: 1500 },
        { item: items.astral_spear, price: 5000 },
        { item: items.ragged_hood, price: 20 },
        { item: items.ragged_armor, price: 40 },
        { item: items.ragged_boots, price: 20 },
        { item: items.hood_of_wisdom, price: 100 },
        { item: items.leather_helmet, price: 220 },
        { item: items.leather_armor, price: 400 },
        { item: items.leather_boots, price: 220 },
        { item: items.plate_helmet, price: 950 },
        { item: items.plate_armor, price: 1500 },
        { item: items.plate_boots, price: 950 },
        { item: items.ring_of_knowledge, price: 300 },
        { item: items.small_recovery_gem, price: 35 },
        { item: items.small_healing_potion, price: 15 },
        { item: items.medium_healing_potion, price: 50 },
        { item: items.large_healing_potion, price: 225 },
        { item: items.small_mana_potion, price: 15 },
        { item: items.medium_mana_potion, price: 120 },
        { item: items.large_mana_potion, price: 550 },
    ],
};
//# sourceMappingURL=merchant.js.map