const dungeons: Dungeon[] = [
  {
    id: "vithail_dungeon",
    beat_stage_to_unlock: "tomb_of_the_mage",
    rooms: [
      new Room({
        id: "vithail_dungeon_1",
        foes: [],
        exit: true,
        isBoss: false,
        loot: [],
        position: { x: 110, y: 110 },
        connections: { east: "vithail_dungeon_2" },
        escapeChance: 1,
      }),
      new Room({
        id: "vithail_dungeon_2",
        foes: [new Enemy(enemies.skeleton) as EnemyBase, new Enemy(enemies.skeleton) as EnemyBase],
        isBoss: false,
        loot: [],
        relative_to: "vithail_dungeon_1",
        position: { x: 20, y: 0 },
        connections: { west: "vithail_dungeon_1", north: "vithail_dungeon_4", east: "vithail_dungeon_3" },
        escapeChance: 0.5,
      }),
      new Room({
        id: "vithail_dungeon_3",
        foes: [new Enemy(enemies.skeleton_brute) as EnemyBase, new Enemy(enemies.skeleton_brute) as EnemyBase],
        isBoss: false,
        loot: [],
        getKeys: ["ruby_key_vithail"],
        relative_to: "vithail_dungeon_2",
        position: { x: 20, y: 0 },
        connections: { west: "vithail_dungeon_2" },
        escapeChance: 0.5,
      }),
      new Room({
        id: "vithail_dungeon_4",
        foes: [new Enemy(enemies.skeleton_knight) as EnemyBase],
        isBoss: false,
        loot: [],
        keysNeeded: ["ruby_key_vithail"],
        relative_to: "vithail_dungeon_2",
        position: { x: 0, y: -20 },
        connections: { south: "vithail_dungeon_2", north: "vithail_dungeon_center_shrine" },
        escapeChance: 0.33,
      }),
      new Room({
        id: "vithail_dungeon_center_shrine",
        foes: [],
        isBoss: false,
        loot: [],
        keysNeeded: [],
        relative_to: "vithail_dungeon_4",
        position: { x: 0, y: -20 },
        connections: { west: "vithail_dungeon_western_corridor", east: "vithail_dungeon_eastern_corridor", south: "vithail_dungeon_4" },
        escapeChance: 1,
        restore: true,
      }),
      new Room({
        id: "vithail_dungeon_western_corridor",
        foes: [new Enemy(enemies.skeleton_knight) as EnemyBase, new Enemy(enemies.skeleton_brute) as EnemyBase],
        isBoss: false,
        loot: [],
        keysNeeded: [],
        relative_to: "vithail_dungeon_center_shrine",
        position: { x: -20, y: 0 },
        connections: { west: "vithail_dungeon_armory", east: "vithail_dungeon_center_shrine" },
        escapeChance: 0.75,
      }),
      new Room({
        id: "vithail_dungeon_armory",
        foes: [],
        isBoss: false,
        loot: [{ id: "", item: "vithail_cursed_sword", amount: 1 }],
        keysNeeded: [],
        relative_to: "vithail_dungeon_western_corridor",
        position: { x: -20, y: 0 },
        connections: { east: "vithail_dungeon_western_corridor", north: "vithail_dungeon_commander_chamber" },
        escapeChance: 1,
      }),
      new Room({
        id: "vithail_dungeon_commander_chamber",
        foes: [new Enemy(enemies.skeleton_mage) as EnemyBase],
        isBoss: false,
        loot: [{ id: "", item: "gold", amount: 300 }],
        getKeys: ["lord_key_vithail"],
        keysNeeded: [],
        relative_to: "vithail_dungeon_armory",
        position: { x: 0, y: -20 },
        connections: { south: "vithail_dungeon_armory" },
        escapeChance: 1,
      }),
      new Room({
        id: "vithail_dungeon_eastern_corridor",
        foes: [new Enemy(enemies.skeleton_brute) as EnemyBase, new Enemy(enemies.skeleton_brute) as EnemyBase],
        isBoss: false,
        loot: [],
        keysNeeded: [],
        relative_to: "vithail_dungeon_center_shrine",
        position: { x: 20, y: 0 },
        connections: { west: "vithail_dungeon_center_shrine", east: "vithail_dungeon_waiting_chamber", south: "vithail_dungeon_treasury" },
        escapeChance: 0.75,
      }),
      new Room({
        id: "vithail_dungeon_treasury",
        foes: [],
        isBoss: false,
        loot: [{ id: "", item: "gold", amount: 200 }],
        keysNeeded: [],
        relative_to: "vithail_dungeon_eastern_corridor",
        position: { x: 0, y: 20 },
        connections: { north: "vithail_dungeon_eastern_corridor" },
        escapeChance: 1,
      }),
      new Room({
        id: "vithail_dungeon_waiting_chamber",
        foes: [new Enemy(enemies.skeleton_knight) as EnemyBase, new Enemy(enemies.skeleton_knight) as EnemyBase],
        isBoss: false,
        loot: [{ id: "", item: "gold", amount: 1000 }],
        keysNeeded: ["lord_key_vithail"],
        relative_to: "vithail_dungeon_eastern_corridor",
        position: { x: 20, y: 0 },
        connections: { west: "vithail_dungeon_eastern_corridor", north: "vithail_dungeon_castle_proper" },
        escapeChance: 0.5,
      }),
      new Room({
        id: "vithail_dungeon_castle_proper",
        foes: [new Enemy(enemies.skeleton_lord) as EnemyBase],
        isBoss: true,
        end: true,
        loot: [{ id: "", item: "gold", amount: 2000 }],
        getKeys: ["vithail_lord_insignia"],
        keysNeeded: [],
        relative_to: "vithail_dungeon_waiting_chamber",
        position: { x: 0, y: -20 },
        connections: { south: "vithail_dungeon_waiting_chamber" },
        escapeChance: 1,
      }),
    ],
  },
];
