const icons: any = {
  str: "gfx/status/biceps.png",
  agi: "gfx/status/acrobatic.png",
  int: "gfx/status/brain.png",
  vit: "gfx/status/weight-lifting-up.png",
  spi: "gfx/status/wisdom.png",
  atk: "gfx/icons/crossed-swords.png",
  hpMax: "gfx/status/heart-plus.png",
  mpMax: "gfx/icons/magic-swirl.png",
  physical: "gfx/status/physical.png",
  magical: "gfx/status/magical.png",
  elemental: "gfx/status/elemental.png",
  physicalDamage: "gfx/status/physical.png",
  magicalDamage: "gfx/status/magical.png",
  elementalDamage: "gfx/status/elemental.png",
  cooldown: "gfx/status/cooldown.png",
  power: "gfx/status/power.png",
  speed: "gfx/status/speedometer.png",
  critRate: "gfx/status/power.png",
  critPower: "gfx/status/power.png",
  weapon: "gfx/icons/piercing-sword.png",
  helmet: "gfx/icons/viking-helmet.png",
  armor: "gfx/icons/armor-vest.png",
  legs: "gfx/icons/steeltoe-boots.png",
  placeholder: "gfx/icons/triple-yin.png",
  penetration: "gfx/icons/cracked-shield.png",
};
