const abilities: any = {
  physical_attack: {
    id: "physical_attack",
    icon: "gfx/abilities/pointy-sword.png",
    type: "attack",
    damageType: "physical",
    power: 1,
    cooldown: 0,
  },
  magical_attack: {
    id: "magical_attack",
    icon: "gfx/abilities/pointy-sword.png",
    type: "attack",
    damageType: "magical",
    power: 1,
    cooldown: 0,
  },
  elemental_attack: {
    id: "elemental_attack",
    icon: "gfx/abilities/pointy-sword.png",
    type: "attack",
    damageType: "elemental",
    power: 1,
    cooldown: 0,
  },
  sharp_strike: {
    id: "sharp_strike",
    icon: "gfx/abilities/pointy-sword.png",
    type: "attack",
    damageType: "physical",
    effectsToEnemy: [effects.wounded],
    cooldown: 5,
    onCooldown: 0,
    power: 1.1,
  },
  heavy_attack: {
    id: "heavy_attack",
    icon: "gfx/abilities/strong.png",
    type: "attack",
    damageType: "physical",
    cooldown: 4,
    onCooldown: 0,
    power: 1.4,
    penetration: 0.1,
  },
};
